version: "2.1"

services:
  caddy:
    build: ./caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    environment:
      DNS_PROVIDER: digitalocean

volumes:
  caddy_data:
  caddy_config: